const nodemailer = require('nodemailer');

// Configure the transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_PORT === '465', // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

/**
 * Sends an email notification.
 * @param {string} to - The recipient email address.
 * @param {string} subject - The subject of the email.
 * @param {string} message - The main body message.
 * @param {string} recipientName - The name of the recipient (optional).
 */
const sendNotificationEmail = async (to, subject, message, recipientName = 'User') => {
  if (!to || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
    return; // Skip if no recipient or missing SMTP credentials
  }

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
      <div style="background-color: #1a5632; color: #ffffff; padding: 25px 20px; text-align: center;">
        <h2 style="margin: 0; font-size: 22px; font-weight: 600; letter-spacing: 0.5px;">University of Southern Mindanao</h2>
        <p style="margin: 5px 0 0 0; font-size: 15px; opacity: 0.9;">Office of the Board Secretary</p>
      </div>
      <div style="padding: 30px; background-color: #ffffff; color: #333333; line-height: 1.6;">
        <p style="font-size: 16px;">Dear <strong>${recipientName}</strong>,</p>
        <div style="background-color: #f8f9fa; border-left: 4px solid #f6c23e; padding: 15px; margin: 20px 0; border-radius: 0 4px 4px 0;">
          <p style="margin: 0; font-size: 15px; color: #2c3e50;">${message}</p>
        </div>
        <p style="font-size: 15px; color: #555555; text-align: center;">Please log in to the USM BoardHub System to view more details or take necessary actions.</p>
        <div style="text-align: center; margin: 25px 0;">
          <a href="https://adco-submit.vercel.app/" style="background-color: #1a5632; color: #ffffff; text-decoration: none; padding: 12px 25px; border-radius: 5px; font-size: 16px; font-weight: bold; display: inline-block; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">Log in to BoardHub</a>
        </div>
        <br/>
        <p style="margin-bottom: 0; font-size: 15px;">Best regards,<br/><strong style="color: #1a5632;">USM BoardHub System</strong></p>
      </div>
      <div style="background-color: #f1f1f1; color: #777777; padding: 15px; text-align: center; font-size: 12px; border-top: 1px solid #e0e0e0;">
        <p style="margin: 0;">This is an automated message generated by the system. Please do not reply to this email.</p>
      </div>
    </div>
  `;

  const textContent = `University of Southern Mindanao\nOffice of the Board Secretary\n\nDear ${recipientName},\n\n${message}\n\nPlease log in to the USM BoardHub System to view more details or take necessary actions: https://adco-submit.vercel.app/\n\nBest regards,\nUSM BoardHub System`;

  try {
    const fromName = process.env.SMTP_FROM_NAME || 'USM BoardHub';
    await transporter.sendMail({
      from: `"${fromName}" <${process.env.SMTP_USER}>`,
      to,
      subject,
      text: textContent,
      html: htmlContent,
    });
    console.log(`Email sent successfully to ${to}`);
  } catch (error) {
    console.error(`Failed to send email to ${to}:`, error.message);
  }
};

module.exports = {
  sendNotificationEmail,
};
