const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const docsDir = path.join(root, 'Iangwapo');
const assetsDir = path.join(docsDir, 'assets');

const GENERATED_NOTE = '> This file is automatically generated by `npm run docs:generate`. Manual edits may be overwritten.';

const routeBaseMap = {
  'authRoutes.js': '/api/auth',
  'userRoutes.js': '/api/users',
  'sucRoutes.js': '/api/sucs',
  'agendaRoutes.js': '/api/agendas',
  'documentRoutes.js': '/api/documents',
  'dateBoardMeetingRoutes.js': '/api/dateboardmeetings',
};

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function readJson(filePath) {
  return JSON.parse(readText(filePath));
}

function writeDoc(relPath, content) {
  const filePath = path.join(root, relPath);
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, content.trimEnd() + '\n', 'utf8');
}

function rel(filePath) {
  return path.relative(root, filePath).replace(/\\/g, '/');
}

function listFiles(dir, options = {}) {
  const { includeExt = null, excludeDirs = [] } = options;
  const results = [];

  function walk(current) {
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        if (excludeDirs.includes(entry.name)) continue;
        walk(full);
      } else {
        if (includeExt && !includeExt.includes(path.extname(entry.name))) continue;
        results.push(full);
      }
    }
  }

  walk(dir);
  return results.sort();
}

function listDirNames(dir) {
  return fs.readdirSync(dir).sort();
}

function extractObjectBlock(text, marker) {
  const start = text.indexOf(marker);
  if (start === -1) return '';
  const braceStart = text.indexOf('{', start);
  if (braceStart === -1) return '';
  let depth = 0;
  for (let i = braceStart; i < text.length; i++) {
    if (text[i] === '{') depth += 1;
    if (text[i] === '}') depth -= 1;
    if (depth === 0) {
      return text.slice(braceStart + 1, i);
    }
  }
  return '';
}

function parseTopLevelKeys(block) {
  const keys = [];
  let depth = 0;
  let buffer = '';
  let readingKey = true;

  for (let i = 0; i < block.length; i++) {
    const ch = block[i];
    if (ch === '{' || ch === '[' || ch === '(') depth += 1;
    if (ch === '}' || ch === ']' || ch === ')') depth -= 1;

    if (depth === 0 && readingKey) {
      if (ch === ':') {
        const key = buffer.trim().replace(/,$/, '');
        if (key && !key.startsWith('//')) keys.push(key);
        buffer = '';
        readingKey = false;
        continue;
      }
      if (ch === ',') {
        buffer = '';
        continue;
      }
      buffer += ch;
    } else if (depth === 0 && !readingKey && ch === ',') {
      readingKey = true;
    }
  }

  return keys
    .map((key) => key.split('\n').pop().trim())
    .filter(Boolean)
    .map((key) => key.replace(/['"`]/g, ''));
}

function parseModel(filePath) {
  const text = readText(filePath);
  const mainSchemaMatch = text.match(/const\s+([A-Za-z0-9_]+Schema)\s*=\s*new\s+mongoose\.Schema\(/);
  const modelName = path.basename(filePath, '.js');
  if (!mainSchemaMatch) {
    return { modelName, fields: [], indexes: [] };
  }

  const schemaName = mainSchemaMatch[1];
  const block = extractObjectBlock(text, `const ${schemaName} = new mongoose.Schema(`);
  const fields = parseTopLevelKeys(block);
  const indexMatches = [...text.matchAll(/\.index\(([^\n]+)\)/g)].map((m) => m[1].trim());
  return { modelName, fields, indexes: indexMatches, source: rel(filePath) };
}

function parseRoutes(filePath) {
  const text = readText(filePath);
  const lines = text.split(/\r?\n/);
  const base = routeBaseMap[path.basename(filePath)] || '/api';
  const routes = [];
  for (const line of lines) {
    const match = line.match(/router\.(get|post|put|delete|patch)\(([^,]+),\s*(.+)\);?/i);
    if (!match) continue;
    const method = match[1].toUpperCase();
    const rawPath = match[2].trim().replace(/['"`]/g, '');
    const middlewareChain = match[3];
    let auth = 'Public';
    if (/authenticate/.test(middlewareChain)) auth = 'Authenticated';
    if (/adminOrAbove|superAdminOnly|adminOnly/.test(middlewareChain)) auth = 'Admin or Above';
    const fullPath = `${base}${rawPath === '/' ? '' : rawPath}`;
    routes.push({ method, path: fullPath, auth, source: rel(filePath) });
  }
  return routes;
}

function parseEnvUsage() {
  const backendFiles = listFiles(path.join(root, 'backend'), {
    includeExt: ['.js'],
    excludeDirs: ['node_modules'],
  });
  const frontendFiles = listFiles(path.join(root, 'frontend'), {
    includeExt: ['.js', '.jsx'],
    excludeDirs: ['node_modules', 'dist'],
  });

  const backendVars = new Set();
  const frontendVars = new Set();

  for (const file of backendFiles) {
    const text = readText(file);
    for (const match of text.matchAll(/process\.env\.([A-Z0-9_]+)/g)) {
      backendVars.add(match[1]);
    }
  }
  for (const file of frontendFiles) {
    const text = readText(file);
    for (const match of text.matchAll(/import\.meta\.env\.([A-Z0-9_]+)/g)) {
      frontendVars.add(match[1]);
    }
  }

  return {
    backend: [...backendVars].sort(),
    frontend: [...frontendVars].sort(),
  };
}

function parseAppRoutes() {
  const appPath = path.join(root, 'frontend', 'src', 'App.jsx');
  const text = readText(appPath);
  const routes = [];
  for (const match of text.matchAll(/<Route\s+path="([^"]+)"/g)) {
    routes.push(match[1]);
  }
  return [...new Set(routes)];
}

function makeTree(dir, depth = 2, prefix = '') {
  const entries = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  const lines = [];
  for (const entry of entries) {
    if (['node_modules', '.git', 'dist'].includes(entry.name)) continue;
    const suffix = entry.isDirectory() ? '/' : '';
    lines.push(`${prefix}${entry.name}${suffix}`);
    if (entry.isDirectory() && depth > 0) {
      lines.push(...makeTree(path.join(dir, entry.name), depth - 1, `${prefix}  `));
    }
  }
  return lines;
}

function mdList(items) {
  return items.map((item) => `- ${item}`).join('\n');
}

function mdTable(headers, rows) {
  const head = `| ${headers.join(' | ')} |`;
  const sep = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`).join('\n');
  return [head, sep, body].filter(Boolean).join('\n');
}

function generateDocs() {
  ensureDir(docsDir);
  ensureDir(assetsDir);

  const now = new Date().toISOString();
  const rootPkg = readJson(path.join(root, 'package.json'));
  const backendPkg = readJson(path.join(root, 'backend', 'package.json'));
  const frontendPkg = readJson(path.join(root, 'frontend', 'package.json'));

  const modelFiles = listFiles(path.join(root, 'backend', 'models'), { includeExt: ['.js'] });
  const routeFiles = listFiles(path.join(root, 'backend', 'routes'), { includeExt: ['.js'] });
  const controllerFiles = listFiles(path.join(root, 'backend', 'controllers'), { includeExt: ['.js'] });
  const pageFiles = listFiles(path.join(root, 'frontend', 'src', 'pages'), { includeExt: ['.jsx'] });
  const componentFiles = listFiles(path.join(root, 'frontend', 'src', 'components'), { includeExt: ['.jsx'] });

  const models = modelFiles.map(parseModel);
  const routes = routeFiles.flatMap(parseRoutes);
  const envVars = parseEnvUsage();
  const appRoutes = parseAppRoutes();

  const rootTree = makeTree(root, 2).join('\n');
  const controllersList = controllerFiles.map((file) => `\`${rel(file)}\``);
  const pagesList = pageFiles.map((file) => `\`${rel(file)}\``);
  const componentsList = componentFiles.map((file) => `\`${rel(file)}\``);

  const routeRows = routes.map((route) => [route.method, route.path, route.auth, `\`${route.source}\``]);
  const modelRows = models.map((model) => [model.modelName, model.fields.join(', '), model.indexes.join('<br>') || 'None', `\`${model.source}\``]);
  const scriptRows = Object.entries(rootPkg.scripts || {}).map(([name, value]) => [name, `\`${value}\``]);
  const depRows = Object.entries({ ...(backendPkg.dependencies || {}), ...(frontendPkg.dependencies || {}) })
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, version]) => [name, version]);

  writeDoc('Iangwapo/01_Project_Overview.md', `
# e-Agenda System: Project Overview

${GENERATED_NOTE}

Generated at: ${now}

## Summary
The e-Agenda System is a full-stack web application for CHED and SUC agenda, reminder, and document management. It includes ${models.length} MongoDB models, ${routes.length} backend route definitions, ${pageFiles.length} page components, and ${componentFiles.length} reusable frontend components.

## Main Business Functions
- Authenticate users and restore sessions with JWTs.
- Manage SUCs and assign them to CHED officials.
- Manage board meeting reminders.
- Upload and serve regular, minutes, and special board meeting PDFs.
- Provide role-specific dashboards and analytics.

## Current Role Model
- \`superadmin\`
- \`admin\`
- \`user\`

## High-Level Inventories
### Backend controllers
${mdList(controllersList)}

### Frontend pages
${mdList(pagesList)}

### Frontend components
${mdList(componentsList)}

## Frontend route paths discovered from App.jsx
${mdList(appRoutes.map((route) => `\`${route}\``))}

## Assumptions
- This documentation is generated from the current repository structure and code patterns.
- Narrative descriptions remain templates, while inventories and references are refreshed automatically.
`);

  writeDoc('Iangwapo/02_System_Architecture.md', `
# System Architecture

${GENERATED_NOTE}

Generated at: ${now}

## Runtime Architecture

~~~mermaid
flowchart LR
    Browser[Browser] --> Frontend[React Frontend]
    Frontend -->|Axios / JSON / Multipart| Backend[Express API]
    Backend --> Mongo[(MongoDB)]
    Backend --> S3[(Optional S3 / Spaces)]
~~~

## Deployment Modes
- Local development: Vite dev server proxies \`/api\` to backend.
- Split deployment: frontend on \`/\`, backend on \`/api\`.
- Vercel/serverless compatibility remains present through \`api/index.js\`.

## Architectural Facts Discovered
- Backend route files: ${routeFiles.length}
- Backend controller files: ${controllerFiles.length}
- Mongoose model files: ${modelFiles.length}
- Frontend route paths discovered: ${appRoutes.length}

## API Surface Inventory
${mdTable(['Method', 'Path', 'Auth', 'Source'], routeRows)}
`);

  writeDoc('Iangwapo/03_Technology_Stack.md', `
# Technology Stack

${GENERATED_NOTE}

Generated at: ${now}

## Root Scripts
${mdTable(['Script', 'Command'], scriptRows)}

## Root Engine
- Node: \`${rootPkg.engines?.node || 'not specified'}\`

## Backend Dependencies
${mdTable(['Package', 'Version'], depRows)}

## Frontend Tooling
- React: \`${frontendPkg.dependencies?.react || 'n/a'}\`
- React Router DOM: \`${frontendPkg.dependencies?.['react-router-dom'] || 'n/a'}\`
- Axios: \`${frontendPkg.dependencies?.axios || 'n/a'}\`
- Vite: \`${frontendPkg.devDependencies?.vite || 'n/a'}\`
- Bootstrap: \`${frontendPkg.dependencies?.bootstrap || 'n/a'}\`

## Environment Variables Discovered in Code
### Backend
${mdList(envVars.backend.map((key) => `\`${key}\``))}

### Frontend
${mdList(envVars.frontend.map((key) => `\`${key}\``))}
`);

  writeDoc('Iangwapo/04_Project_Structure.md', `
# Project Structure

${GENERATED_NOTE}

Generated at: ${now}

## Repository Tree

~~~text
${rootTree}
~~~

## Backend Modules
${mdList(controllerFiles.map((file) => `\`${rel(file)}\``))}

## Route Modules
${mdList(routeFiles.map((file) => `\`${rel(file)}\``))}

## Model Modules
${mdList(modelFiles.map((file) => `\`${rel(file)}\``))}

## Frontend Pages
${mdList(pageFiles.map((file) => `\`${rel(file)}\``))}

## Frontend Components
${mdList(componentFiles.map((file) => `\`${rel(file)}\``))}
`);

  writeDoc('Iangwapo/05_Database_Documentation.md', `
# Database Documentation

${GENERATED_NOTE}

Generated at: ${now}

## Models
${mdTable(['Model', 'Top-level fields', 'Indexes', 'Source'], modelRows)}

## Relationship Diagram
~~~mermaid
erDiagram
    SUC ||--o{ AGENDA : owns
    SUC ||--o{ DOCUMENT : owns
    SUC ||--o{ DATEBOARDMEETING : schedules
    USER }o--o{ SUC : scopes_access
~~~

## Notes
- Top-level fields are derived from the schema object blocks.
- Some logical relationships use abbreviations and OCC codes rather than hard foreign keys.
`);

  writeDoc('Iangwapo/06_Backend_Documentation.md', `
# Backend Documentation

${GENERATED_NOTE}

Generated at: ${now}

## Core Entry Points
- \`backend/server.js\`
- \`api/index.js\`
- \`backend/seed.js\`

## Controllers
${mdList(controllerFiles.map((file) => `\`${rel(file)}\``))}

## Route Definitions
${mdTable(['Method', 'Path', 'Auth', 'Source'], routeRows)}

## Environment Variables Used by Backend
${mdList(envVars.backend.map((key) => `\`${key}\``))}

## Generated Notes
- The backend mounts routes with and without an \`/api\` prefix.
- File endpoints support JWTs in either the Authorization header or query parameter.
- Seeding is triggered automatically on startup when no users exist.
`);

  writeDoc('Iangwapo/07_Frontend_Documentation.md', `
# Frontend Documentation

${GENERATED_NOTE}

Generated at: ${now}

## App Routes
${mdList(appRoutes.map((route) => `\`${route}\``))}

## Page Components
${mdList(pageFiles.map((file) => `\`${rel(file)}\``))}

## Shared Components
${mdList(componentFiles.map((file) => `\`${rel(file)}\``))}

## API Client Behavior
- Development mode uses \`/api\` so Vite can proxy locally.
- Production mode uses \`VITE_API_BASE_URL\`.
- JWT is attached to requests when present in \`localStorage\`.

## Frontend Environment Variables
${mdList(envVars.frontend.map((key) => `\`${key}\``))}
`);

  writeDoc('Iangwapo/08_API_Documentation.md', `
# API Documentation

${GENERATED_NOTE}

Generated at: ${now}

## Route Inventory
${mdTable(['Method', 'Path', 'Auth', 'Source'], routeRows)}

## Conventions
- Main production base path: \`/api\`
- Auth header: \`Authorization: Bearer <token>\`
- Upload content type: \`multipart/form-data\`

## Caveats
- Auth levels are inferred from route middleware, then refined by controller logic.
- Some platform deployments may trim the \`/api\` prefix before forwarding.
`);

  writeDoc('Iangwapo/09_Installation_Guide.md', `
# Installation Guide

${GENERATED_NOTE}

Generated at: ${now}

## Root Scripts
${mdTable(['Script', 'Command'], scriptRows)}

## Quick Start
~~~powershell
npm run install:all
cd backend
npm run seed
npm run dev
~~~

In another terminal:
~~~powershell
cd frontend
npm run dev
~~~

## Environment Variables
### Backend
${mdList(envVars.backend.map((key) => `\`${key}\``))}

### Frontend
${mdList(envVars.frontend.map((key) => `\`${key}\``))}
`);

  writeDoc('Iangwapo/10_User_Guide.md', `
# User Guide

${GENERATED_NOTE}

Generated at: ${now}

## Main User Flows
- Log in with username/password.
- View role-specific dashboards.
- Upload agenda and meeting PDFs.
- Manage reminders and profiles according to role.

## Screen Inventory
${mdList(pageFiles.map((file) => `\`${path.basename(file, '.jsx')}\``))}
`);

  writeDoc('Iangwapo/11_Developer_Guide.md', `
# Developer Guide

${GENERATED_NOTE}

Generated at: ${now}

## Documentation Automation
- Generate docs once: \`npm run docs:generate\`
- Watch and regenerate docs on code changes: \`npm run docs:watch\`

## High-Value Files
- \`backend/server.js\`
- \`backend/middleware/auth.js\`
- \`frontend/src/App.jsx\`
- \`frontend/src/services/api.js\`

## Current Inventories
### Controllers
${mdList(controllerFiles.map((file) => `\`${rel(file)}\``))}

### Models
${mdList(modelFiles.map((file) => `\`${rel(file)}\``))}

### Routes
${mdList(routeFiles.map((file) => `\`${rel(file)}\``))}
`);

  writeDoc('Iangwapo/12_Security_Documentation.md', `
# Security Documentation

${GENERATED_NOTE}

Generated at: ${now}

## Security-Relevant Components
- JWT-based auth via backend middleware
- bcrypt password hashing
- CORS allowlist handling
- PDF-only upload restrictions

## Environment Variables Relevant to Security
${mdList(envVars.backend.filter((key) => /JWT|S3|ALLOWED|MONGO/.test(key)).map((key) => `\`${key}\``))}

## Current Risks
- JWT is stored in \`localStorage\` on the client.
- Query-token file access is supported for PDF tabs.
- No automatic rate limiting is visible in the codebase.
`);

  writeDoc('Iangwapo/13_Maintenance_Guide.md', `
# Maintenance Guide

${GENERATED_NOTE}

Generated at: ${now}

## Routine Tasks
- Regenerate documentation after code changes.
- Rebuild frontend after env or API changes.
- Verify \`/api/health\` in deployed environments.
- Review dependencies and storage growth.

## Useful Commands
~~~powershell
npm run docs:generate
npm run docs:watch
npm --prefix frontend run build
~~~
`);

  writeDoc('Iangwapo/14_Troubleshooting.md', `
# Troubleshooting

${GENERATED_NOTE}

Generated at: ${now}

## Common Problems
- Local dev login failing because frontend points to production API.
- Production \`/api\` route returning 404 due to platform routing.
- DNS errors from invalid \`VITE_API_BASE_URL\` values.
- MongoDB connection failures from bad credentials or trusted-source settings.

## Quick Checks
- Backend health: \`/health\` and \`/api/health\`
- Local dev API path should resolve through Vite proxy
- Confirm frontend env values before production build
`);

  writeDoc('Iangwapo/15_Future_Enhancements.md', `
# Future Enhancements

${GENERATED_NOTE}

Generated at: ${now}

## Engineering Priorities
- Add automated tests.
- Add request schema validation.
- Add API schema generation.
- Improve auth/session hardening.
- Expand document lifecycle and analytics features.
`);

  writeDoc('Iangwapo/assets/architecture-diagram.md', `
# Architecture Diagram

${GENERATED_NOTE}

~~~mermaid
flowchart LR
    Browser[Browser] --> Frontend[React Frontend]
    Frontend --> Backend[Express API]
    Backend --> Mongo[(MongoDB)]
    Backend --> S3[(Optional S3 / Spaces)]
~~~
`);

  writeDoc('Iangwapo/assets/database-schema.md', `
# Database Schema Diagram

${GENERATED_NOTE}

~~~mermaid
erDiagram
    SUC ||--o{ AGENDA : owns
    SUC ||--o{ DOCUMENT : owns
    SUC ||--o{ DATEBOARDMEETING : schedules
    USER }o--o{ SUC : scopes_access
~~~

## Model Inventory
${mdTable(['Model', 'Fields'], models.map((model) => [model.modelName, model.fields.join(', ')]))}
`);

  writeDoc('Iangwapo/assets/flowcharts.md', `
# Flowcharts

${GENERATED_NOTE}

## Login Flow
~~~mermaid
flowchart TD
    Start[Open login] --> Submit[Submit credentials]
    Submit --> Backend[POST auth route]
    Backend --> Check{Valid?}
    Check -->|Yes| Token[Return JWT]
    Check -->|No| Error[Return error]
~~~

## Upload Flow
~~~mermaid
flowchart TD
    File[Select PDF] --> Upload[Submit multipart request]
    Upload --> Validate[Validate file type and size]
    Validate --> Store[Store in MongoDB or S3]
    Store --> Refresh[Refresh UI state]
~~~
`);

  console.log(`Documentation generated at ${now}`);
}

function watchDocs() {
  const watchTargets = [
    path.join(root, 'backend'),
    path.join(root, 'frontend'),
    path.join(root, 'api'),
    path.join(root, 'package.json'),
    path.join(root, 'vercel.json'),
  ];

  let timer = null;
  const schedule = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        generateDocs();
      } catch (error) {
        console.error('Documentation generation failed:', error);
      }
    }, 250);
  };

  generateDocs();
  console.log('Watching for documentation-relevant changes...');

  for (const target of watchTargets) {
    if (!fs.existsSync(target)) continue;
    const stat = fs.statSync(target);
    if (stat.isDirectory()) {
      fs.watch(target, { recursive: true }, (eventType, filename) => {
        if (!filename) return;
        if (/node_modules|dist|Iangwapo|\.git/.test(filename)) return;
        schedule();
      });
    } else {
      fs.watchFile(target, { interval: 500 }, schedule);
    }
  }
}

if (process.argv.includes('--watch')) {
  watchDocs();
} else {
  generateDocs();
}